name: test

on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ${{ github.ref_name == 'develop' && 'develop' || github.ref_name == 'staging' && 'staging' || '' }}


jobs:
  env-test:
    runs-on: ubuntu-latest
    if: env.WORKING_DIRECTORY != ''
    steps:
      - name: echo WORKING_DIRECTORY
        run: echo ${{ env.WORKING_DIRECTORY }}
