name: test

on:
  push:
    branches:
      - develop
      - staging
      - production

  workflow_dispatch:
#    inputs:
#      environment:
#        description: Choose environment
#        required: true
#        type: choice
#        options:
#            - develop
#            - staging
#            - production

jobs:
  deployment-on-dev:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    environment: develop
    steps:
      - name: echo variables
        run: echo ${{ vars.NON_SECRET_ENV_NAME }}
      - name: echo secrets
        run: echo ${{ secrets.SECRET_ENV_NAME }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: create tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: dev ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  deployment-on-stg:
    runs-on: ubuntu-latest
    if: github.ref_name == 'staging'
    environment: staging
    steps:
      - name: echo variables
        run: echo ${{ vars.NON_SECRET_ENV_NAME }}
      - name: echo secrets
        run: echo ${{ secrets.SECRET_ENV_NAME }}
      
  deployment-on-prod:
    runs-on: ubuntu-latest
    if: github.ref_name == 'production'
    environment: production
    steps:
      - name: echo variables
        run: echo ${{ vars.NON_SECRET_ENV_NAME }}
      - name: echo secrets
        run: echo ${{ secrets.SECRET_ENV_NAME }}
      