name: test

on:
  push:
    branches:
      - develop
      - staging
      - production

  workflow_dispatch:
#    inputs:
#      environment:
#        description: Choose environment
#        required: true
#        type: choice
#        options:
#            - develop
#            - staging
#            - production

jobs:
  deployment-on-dev:
    runs-on: ubuntu-latest
    if: github.ref_name == 'develop'
    environment: develop
    steps:
      - name: echo secrets
        run: echo ${{ secrets.SECRET_ENV_NAME }}
      - name: echo variables
        run: echo ${{ vars.NON_SECRET_ENV_NAME }}

  deployment-on-stg:
    runs-on: ubuntu-latest
    if: github.ref_name == 'staging'
    environment: staging
    steps:
      - name: echo secrets
        run: echo ${{ secrets.SECRET_ENV_NAME }}
      - name: echo variables
        run: echo ${{ vars.NON_SECRET_ENV_NAME }}
      
  deployment-on-prod:
    runs-on: ubuntu-latest
    if: github.ref_name == 'production'
    environment: production
    steps:
      - name: echo secrets
        run: echo ${{ secrets.SECRET_ENV_NAME }}
      - name: echo variables
        run: echo ${{ vars.NON_SECRET_ENV_NAME }}
      